services:
  database_ml:
    container_name: mongo_ml
    image: mongo
    restart: unless-stopped
    env_file: .env
    # Надо закрыть порты при выкатке решения, я их открыл чтобы чекать че в бд лежит через vs code
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - db_ml_data:/data/db

  ml_webserver:
    build:
      context: /
    container_name: ml_local
    restart: unless-stopped
    env_file: .env
    environment:
      HOST: ml
    ports:
      - 8000:8010
    depends_on:
      - database_ml

volumes:
  db_ml_data:
  caddy_data:
  caddy_config: