services:
  database:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
      - ./create_local_user.js:/docker-entrypoint-initdb.d/create_local_user.js

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8010:8010
    env_file: .env
    depends_on:
      database:
        condition: service_started

  ml:
    container_name: ml
    restart: unless-stopped
    env_file: .env
    build:
      context: ml
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      ML_HOST: ${ML_HOST}
    depends_on:
      database:
        condition: service_started

volumes:
  db_data:
  caddy_data:
  caddy_config: