services:
  database:
    container_name: mongo
    image: mongo
    platform: linux/arm64
    restart: unless-stopped
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
      - ./create_local_user.js:/docker-entrypoint-initdb.d/create_local_user.js

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    cap_add: [ NET_ADMIN ]
    ports: [ 80:80 ]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file: .env

  backend:
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      APP_PORT: ${BACKEND_PORT}
      APP_HOST: ${BACKEND_HOST}
    ports:
      - 8010:8010
    depends_on:
      database:
        condition: service_started
      frontend:
        condition: service_started

  ml:
    container_name: ml
    restart: unless-stopped
    env_file: .env
    environment:
      ML_PORT: '8000'
      ML_HOST: 'ml'
    build:
      context: ml
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_started
      frontend:
        condition: service_started

volumes:
  db_data:
  caddy_data:
  caddy_config: