services:
  database:
    image: mongo
    platform: linux/arm64
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_data:/data/db
      - ./create_local_user.js:/docker-entrypoint-initdb.d/create_local_user.js

  frontend:
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    cap_add: [ NET_ADMIN ]
    ports: [ 80:80 ]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    env_file: .env
    
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mongo

  backend:
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      database:
        condition: service_started
      frontend:
        condition: service_started

  ml:
    restart: unless-stopped
    env_file: .env
    build:
      context: ml
      dockerfile: Dockerfile
    environment:
      - HOST = 0.0.0.0
    depends_on:
      database:
        condition: service_started
      frontend:
        condition: service_started

volumes:
  db_data:
  caddy_data:
  caddy_config: